package com.atn.app.webservices;

public class WebserviceType
{

	public static enum ServiceType
	{
		FOURSQUARE,
		FOURSQUARE_LOCATION,
		INSTAGRAM_LOCATION,
		INSTAGRAM_MEDIA,
		
		LOGIN,
		REGISTER,
		PASSWORD_RECOVERY,
		CHECK_USER,
		CHECK_EMAIL,
		
		ATN_REGISTERED_BARS,
		
		FORUM_LIST,
		FORUM_POST,
		
		ADD_DEALS,
		
		CONTACT_ATN,
		SHARE_ATN_BARS,
		FAVORITE_ATN_BARS,
		
		UPDATE_ACCESS_TOKEN,
		SUBSCRIBE_ACCESS_TOKEN,
		UNSUBSCRIBE_ACCESS_TOKEN,
		
		UPDATE_USER_PROFILE,
		
		USERS_FAVORITES,
		
		CHANGE_PASSWORD,
		
		SHARE_PROMOTION,
		SHARE_BUSINESS,
		REDEEM_PROMOTION,
		BUSINESS_FAVORITES,
		BUSINESS_UNFAVORITES,
		CLAIM_PROMOTION,
		EXPIRE_PROMOTION,
		
		BUSINESS_SUBSCRIBE,
		BUSINESS_UNSUBSCRIBE,
		BUSINESS_SUBSCRIBE_ALL,
		BUSINESS_UNSUBSCRIBE_ALL,
		
		NON_ATN_FAVORITE,
		NON_ATN_UNFAVORITE,
		MY_DEAL
	}
	
}
